#lang racket
(define (gcd a b)
  (if (= b 0)
      a
      (gcd b (remainder a b))))

;;(gcd 279 15) is generated by iterative.

;;Substitution model:
;;(gcd 279 15)
;;(gcd 15 (remainder 279 15)
;;(gcd 15 9)
;;(gcd 9 (remainder 15 9)
;;(gcd 9 6)
;;(gcd 6 (remainder 9 6))
;;(gcd 6 3)
;;(gcd 3 (remainder 6 3)
;;(gcd 3 0)
;;3